### ISSUE TITLE
Setting value 'True' is not equals to 'true'

### ISSUE THREAD

**Issue by YanWittmann** [Skyball2000/launch-anything#24]
The boolean setting editor sets boolean values to `True` and not `true` which means that the matcher detects it as `false`

**Comment by fabridan** [comment]
Hi, 
I would like to fix this bug. 
May I ask you for a better description? Can you please assign it to me?

**Comment by YanWittmann** [comment]
Wait, someone else actually uses this? I never put much thought into these issues when writing and assigning them because this has mainly been a project I worked on myself. That's so cool, how did you find this? :-)

I've actually already fixed but not commited it yet, but if you want you can find a different issue to work on!

**Comment by YanWittmann** [comment]
@fabridan okay, but I've got to know how exactly you found this project and stuff, like, I mean I didn't expect anyone else here beside me ;-)

**Comment by fabridan** [comment]
@Skyball2000 I was looking for a java project that was not for Android. : )
