### ISSUE TITLE
Chart division by 0 and other errors catch

### ISSUE THREAD

**Issue by YanWittmann** [Skyball2000/launch-anything#26]

**Comment by fabridan** [comment]
Hi, 
I would like to fix this bug. 
May I ask you for a better description? Can you please assign it to me?

**Comment by YanWittmann** [comment]
Okay, here's a better description:

The runtime tile `ChartGeneratorTile` has the function `solveForValue` that catches `UnknownFunctionOrVariableException` but `java.lang.ArithmeticException: Division by zero!` is not being caught. Maybe simply catch `Exception` to account for all kinds of exceptions in the calculations.

**Comment by YanWittmann** [comment]
Here you go, have fun!

**Comment by fabridan** [comment]
Hi,
I created a pull request.
