### ISSUE TITLE
Getting the previous input does not place focus on input text field

### ISSUE THREAD

**Issue by YanWittmann** [Skyball2000/launch-anything#27]

**Comment by fabridan** [comment]
Hi,
May I ask you for a better description? I tried but It seems work.

**Comment by YanWittmann** [comment]
Yeah I've just noticed that it works on my laptop, but not on my computer. I will have to look into this a bit more.

**Comment by YanWittmann** [comment]
Okay, this issue does not seem to happen any more. Must have been something different.
