### ISSUE TITLE
Getting previous inputs too fast will cause the application to loop infinitely

### ISSUE THREAD

**Issue by YanWittmann** [Skyball2000/launch-anything#28]

**Comment by fabridan** [comment]
Hi, 
I would like to fix this bug. 
May I ask you for a better description? Can you please assign it to me?

**Comment by YanWittmann** [comment]
I've only created this issue because the bar didn't respond (didn't react to any input, didn't close or anything) after scrolling through the last inputs using the up and down arrows. I'm not sure, I will have to look into this later.

**Comment by YanWittmann** [comment]
Okay, the problem lies a bit deeper than that. To reproduce, simply type in any input and press enter. Bring the bar up again and scroll up using alt+arrow up. This will cause the bar to get caught in some sort of an infinite loop and never come back.
